### ISSUE TITLE
Fehlerabfänge bei der Keyword Abfrage

### ISSUE THREAD

**Issue by as224** [meritback/PBL_tool#1]
- Keywords wie Beispielsweise "life support" (also mit einem Leerzeichen zwischen zwei Worten) rufen einen Fehler hervor.
- Falls keine Keywords eingegeben wurden, erhält man trotzdem ein Ergebnis. (Zum Bsp. Keywords: "", Published in the last 5 years: true -> wirft einen Bug ODER Keywords: "", Published in the last 5 years: true, Amount for results: "10" -> wirft auch einen Bug)
- Es wäre gut, wenn ihr spezifiziert, was man als User für Keywords eingeben kann und in welcher Form man sie eingeben kann. (zum Bsp. "cancer; "life support"") 
- Wenn man nur das Keyword "cancer" oder "rost" eingibt, dann wird ein Fehler geworfen. (Ein Fix wäre hier wahrscheinliche, dass "Amount for results" default mäßig auf eine Zahl >0 gesetzt sein sollte -> User input is required.)

Eure Mai & Aïsha

**Comment by meritback** [comment]
Thank you for the suggestions! If you use the runner.py script with the argument parser, you can use -h or --help to get instructions on how it works. In this case, you have to replace " " by "+" to search for multiple words. On the html page everything should work just fine:)
