### ISSUE TITLE
Amount of results

### ISSUE THREAD

**Issue by as224** [meritback/PBL_tool#2]
Der Fehler ist, dass wir bei "Amount of results" "-1" eingeben können und wir 99 Artikel bekommen.

Euer Maximum bei "Amount of results" ist 100 (bezogen auf die Artikel, die ausgegeben werden), aber wenn wir bspw. 105 eingeben, dann bekommen wir trotzdem nur 100 Artikel zurück. (Fehlermeldung wäre hier gut.)

Eure Mai & Aïsha

**Comment by meritback** [comment]
Thank you very much, we fixed the problem and will specify on the webpage, what the number input means.
