### ISSUE TITLE
Anmerkungen und Verbesserungsvorschläge 

### ISSUE THREAD

**Issue by as224** [meritback/PBL_tool#3]
- Wenn die ID bei der Ausgabe der Artikel "Pubmed ID" heißen würde, dann würde der/die User/in sofort verstehen, welchen Sinn diese ID hat.
- Ein Return-Button zur Start Seite wäre nutzer*innen-freundlich.
- Ihr bentutz die ncbi URL. Wenn ihr die Pubmed URL benutzt, dann könntet ihr den Sort Algorithm "bequem" miteinbauen. (https://pubmed.ncbi.nlm.nih.gov/?term=cancer&sort=date -> "sort=date")
- Mehr Kommentare würden euren Code verständlicher machen.

- Sonst habt ihr ein cooles Programm! Falls ihr Fragen zu den Issues habt, dann meldet euch gerne. 
Eure Mai & Aïsha

**Comment by meritback** [comment]
Thanks a lot, for all your useful advice, we will work on the comments and implement the return button. 
In the script start.py we are sorting the data frame by column, which is very easy too and works well for us.
